from __future__ import annotations

import itertools
import math

import numpy as np

SEED = 20260531


def random_zonotope_generators(rng: np.random.Generator, n: int, count: int) -> np.ndarray:
    """Rows are generating segments for a full-dimensional random zonotope."""
    return rng.normal(size=(count, n))


def mixed_zonotope_volume(k_generators: np.ndarray, l_generators: np.ndarray, m: int) -> float:
    """Mixed volume V(K[n-m], L[m]) for zonotopes generated by row vectors."""
    n = k_generators.shape[1]
    generators = [(row, 0) for row in k_generators] + [(row, 1) for row in l_generators]
    coefficient = 0.0

    for selected in itertools.combinations(range(len(generators)), n):
        if sum(generators[index][1] for index in selected) != m:
            continue
        matrix = np.vstack([generators[index][0] for index in selected]).T
        coefficient += abs(np.linalg.det(matrix))

    return coefficient * math.factorial(n - m) * math.factorial(m) / math.factorial(n)


def F(k_generators: np.ndarray, l_generators: np.ndarray, m: int) -> float:
    return mixed_zonotope_volume(k_generators, l_generators, m) / mixed_zonotope_volume(
        k_generators, l_generators, 1
    )


def midpoint_search() -> list[str]:
    rng = np.random.default_rng(SEED)
    lines = [f"Random seed: {SEED}", "", "Random zonotope midpoint search:"]
    cases = [(4, 5, 120), (4, 7, 60), (5, 6, 60), (5, 7, 25)]

    for n, generator_count, trials in cases:
        found_violation = False
        for trial in range(trials):
            k0 = random_zonotope_generators(rng, n, generator_count)
            k1 = random_zonotope_generators(rng, n, generator_count)
            l_body = random_zonotope_generators(rng, n, generator_count)
            midpoint = np.vstack([0.5 * k0, 0.5 * k1])

            f0 = {m: F(k0, l_body, m) for m in range(2, n + 1)}
            f1 = {m: F(k1, l_body, m) for m in range(2, n + 1)}
            fm = {m: F(midpoint, l_body, m) for m in range(2, n + 1)}

            for m in range(2, n + 1):
                endpoint_average = 0.5 * (f0[m] + f1[m])
                if fm[m] > endpoint_average + 1e-9:
                    lines.append(
                        "violation "
                        f"n={n} generators={generator_count} trial={trial} m={m} "
                        f"midpoint={fm[m]:.12g} endpoint_average={endpoint_average:.12g} "
                        f"gap={fm[m] - endpoint_average:.12g}"
                    )
                    found_violation = True
                    break
            if found_violation:
                break

        lines.append(
            f"n={n}, generators={generator_count}, trials={trials}, "
            f"violation_found={found_violation}"
        )

    return lines


if __name__ == "__main__":
    for line in midpoint_search():
        print(line, flush=True)
